# Generated by Django 4.0.4 on 2022-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=1000, null=True)),
                ('result', models.CharField(max_length=1000, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Histpersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=1000, null=True)),
                ('date', models.CharField(max_length=1000, null=True)),
                ('result', models.CharField(max_length=1000, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
